all:
  children:
    test:
      hosts:
        host1:
          ansible_host: 192.168.206.130
          ansible_port: 2211
          ansible_user: admin
        host2:
          ansible_host: 192.168.206.132
          ansible_port: 22
          ansible_user: admin
        host3:
          ansible_host: 192.168.206.133
          ansible_port: 22
          ansible_user: admin
