---
- name: SSH 공개키 배포
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: .ssh 디렉토리 생성
      raw: mkdir -p ~/.ssh && chmod 700 ~/.ssh

    - name: 공개키 등록
      raw: |
        grep -qxF "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEppgd2A1CqJ5sdtdQQLYBCIEXwOnZhpI7VnRb2kJCPS admin@localhost.localdomain" ~/.ssh/authorized_keys || \
        echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEppgd2A1CqJ5sdtdQQLYBCIEXwOnZhpI7VnRb2kJCPS admin@localhost.localdomain" >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
